apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrator
  namespace: NAMESPACE
  labels:
    app: migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrator
  template:
    metadata:
      labels:
        app: migrator
    spec:
      containers:
      - name: migrator
        image: REGISTRY/storage-version-migration-migrator:VERSION
        command:
          - /migrator
          - --v=2
          - --alsologtostderr
          - --kube-api-qps=40
          - --kube-api-burst=1000
